# ── Datasource ──────────────────────────────────────────
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:password}

#datasource should be disabled to run ./mvnw verify or enabled but with running docker
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/jammy-profile-db

# ── Liquibase ────────────────────────────────────────────
# Liquibase minimal config properties
quarkus.liquibase.migrate-at-start=true

# Liquibase optional config properties
%dev.quarkus.liquibase.contexts=dev
%test.quarkus.liquibase.contexts=!dev

# ── S3 ───────────────────────────────────────────────────
quarkus.s3.endpoint-override=${S3_ENDPOINT_OVERRIDE:http://localhost:4566}
quarkus.s3.aws.region=${AWS_REGION:us-east-1}
quarkus.s3.aws.credentials.type=${AWS_CREDENTIALS_TYPE:static}
quarkus.s3.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY_ID:test-key}
quarkus.s3.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_ACCESS_KEY:test-secret}
bucket.name=${AWS_S3_BUCKET_NAME:jammy-media}
quarkus.s3.path-style-access=${S3_PATH_STYLE_ACCESS:false}
quarkus.s3.checksum-validation=false
quarkus.s3.sync-client.type=aws-crt

# ── OIDC ─────────────────────────────────────────────────
%dev.quarkus.oidc.auth-server-url=http://localhost:8180/realms/jammy
%dev.quarkus.oidc.client-id=jammy-profile-service
%dev.quarkus.oidc.application-type=service

quarkus.oidc.auth-server-url=${AUTH_SERVER_URL:http://localhost:8180/realms/jammy}
quarkus.oidc.client-id=${OIDC_CLIENT_ID:jammy-profile-service}
quarkus.oidc.application-type=service
